### ISSUE TITLE
Transaction LC Multi-Insert

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/pharus#124]
Allow a custom multi-insert query to be defined by the spec and insert in a transaction

**Comment by mkosma** [comment]
# USER STORIES
As a researcher, I want Works to organize and show me screens for a project in a way that matches whether I'm setting up an experiment, defining its subjects, entering and uploading experimental data, or viewing the results of my analysis.

As the DataJoint team, I want Works to automatically interpret and render a workflow instead of relying on a separate data entry spec, so that we can easily add and customize workflows while minimizing the need to develop and test new specs for each workflow, the need for version control on standard workflows and specs, and the risk of errors whenever a workflow is changed or customized.

**Comment by mkosma** [comment]
[ ] define query identifying the data fields (tables, fields, relationships, data types) to be displayed and updated within each Activity of a Project, and define a SciViz spec containing the query and its interface
[ ] parse the query spec into Pharus



[ ] define API spec (URI, parameters, return value) that instructs the front end how to render the data entry screens for a Project
[ ] define a JSON return value with the info needed to render the ePhys data entry screens and elements
[ ] insert the ePhys JSON as a constant in the front end
[ ] add API function into Pharus on Percona, returning the ePhys JSON constant
[ ] update front end to fetch a Project's workflow config from Pharus API (fetch & cache per browser session)
[ ] decide whether to define constants or write an algorithm to support next workflows
[ ] add algorithm or lookup to API covering the standard workflows for release

**Comment by guzman-raphael** [comment]
Specification for `GET` attributes route:
- route: configured through `attributes_route_format` but defaulting to `/{route}/attributes`
- SciViz specification:
  ```yaml
  form1:
    route: /session
    x: 1
    y: 2
    height: 1
    width: 1
    type: form
    tables:
      - session.Session
      - session.SessionDirectory
      - session.SessionNote
    display:  # optional, default to tables order and DB definitions
      - type: attribute
        input: Session Id
        destination: session_id
      - type: attribute
        input: Session Date
        destination: session_datetime
      - type: table # order here respected in response/UI
        input: Animal
        destination: Subject
        display:
          - type: attribute
            input: Subject Name
            destination: subject_name
          - type: attribute
            destination: subject_sex
      - type: attribute
        input: Session Directory
        destination: session_dir
      - type: attribute #omitted input means display is session_note
        destination: session_note
    ```
- Request payload: Empty
- Response payload:
  ```json
  {
    "attributes": [
      {
        "type": "attribute",
        "datatype": "int",
        "name": "Session Id"
      },
      {
        "type": "attribute",
        "datatype": "datetime",
        "name": "Session Date"
      },
      {
        "type": "table",
        "values": [
          [{"Subject Name": "Alpha", "subject_sex": "M"}],
          [{"Subject Name": "Alpha", "subject_sex": "F"}],
          [{"Subject Name": "Beta", "subject_sex": "U"}]
        ],
        "name": "Animal"
      },
      {
        "type": "attribute",
        "datatype": "varchar(100)",
        "name": "Session Directory"
      },
      {
        "type": "attribute",
        "datatype": "varchar(300)",
        "name": "session_note"
      }
    ]
  }
  ```
