### ISSUE TITLE
`Field <field> doesn't have a default value` error when providing a table field mapping that matches the table's PK

### ISSUE THREAD

**Issue by A-Baji** [datajoint/pharus#161]
Example:
```
- type: table
  input: A Id
  destination: test_group1_simple.TableA
  map:
    - type: attribute
      input: A Id
      destination: a_id
```
Or:
```
- type: table
  input: a_id
  destination: test_group1_simple.TableA
```

This is due to the [map flattening step](https://github.com/datajoint/pharus/blob/master/pharus/component_interface.py#L244), where the table's PK mapping gets overwritten by the table's mapping due to them having the same key.
